sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1024
  alioss:
    access-key-id: LTAI5tMPNYSPbzUqzsv9norK
    access-key-secret: y5LvhwBwWZSskihT0cXOczc1EXx01R
    bucket-name: netpure
    endpoint: oss-cn-beijing.aliyuncs.com
  wechat:
    appid: wxebf17807852a6102
    secret: d67afe4267e4067d5c8f5962dda4479b

spring:
  redis:
    host: 20.78.38.216
    port: 6379
    password: jhkdjhkjdhsIUTYURTU_hzMrap