sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1024
  alioss:
    access-key-id: LTAI5tMPNYSPbzUqzsv9norK
    access-key-secret: y5LvhwBwWZSskihT0cXOczc1EXx01R
    bucket-name: netpure
    endpoint: oss-cn-beijing.aliyuncs.com

spring:
  redis:
    host: 192.168.1.118
    port: 6379
    password: 10241024
